from pathlib import Path
import json,html,os
P=Path(__file__).resolve().parent
E=html.escape
articles=json.loads((P/'content/articles.json').read_text())
data=json.loads((P/'content/ratings.json').read_text()); developers=data['developers']; complexes=data['complexes']
SITE=os.getenv('SITE_URL','https://nickbelsov.github.io/anastasia-shubina').rstrip('/')
IRN='https://www.irn.ru/news/160754-nazvany-krupneyshie-zastroyschiki-moskvy-i-oblasti.html'
URBAN='https://uawards.ru/news/all/pobediteli_premii_urban_2025_moskva'
def shell(title,desc,body,route='',depth=0,article=False):
 prefix='../'*depth
 schema={'@context':'https://schema.org','@type':'WebPage','name':title,'description':desc,'url':SITE+'/'+route,'inLanguage':'ru'}
 if route=='': schema={'@context':'https://schema.org','@type':'Person','name':'Анастасия Шубина','jobTitle':'Эксперт по жилой недвижимости','url':SITE,'sameAs':['https://vk.ru/id_1000000000','https://www.instagram.com/nastia_shubina/']}
 return f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)}</title><meta name="description" content="{E(desc)}"><meta name="theme-color" content="#ffffff"><link rel="canonical" href="{SITE}/{route}"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(desc)}"><meta property="og:type" content="{'article' if article else 'website'}"><meta property="og:url" content="{SITE}/{route}"><meta property="og:locale" content="ru_RU"><link rel="icon" href="{prefix}assets/favicon.svg"><link rel="stylesheet" href="{prefix}assets/style.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script defer src="{prefix}assets/app.js"></script></head><body><a class="skip" href="#main">Перейти к содержанию</a><div class="progress" aria-hidden="true"></div><header><nav aria-label="Главная навигация"><a class="brand" href="{prefix}index.html">Анастасия Шубина<small>НЕДВИЖИМОСТЬ · МОСКВА</small></a><button class="menu" aria-expanded="false" aria-controls="nav-links">Меню</button><div class="links" id="nav-links"><a href="{prefix}guide/">Как выбрать</a><a href="{prefix}developers/">Застройщики</a><a href="{prefix}complexes/">Жилые комплексы</a><a href="{prefix}blog/">Блог</a><a class="pill" href="{prefix}index.html#contact">Связаться</a></div></nav></header><main id="main">{body}</main><footer><div class="wrap foot"><span>© 2026 Анастасия Шубина · Москва и Московская область</span><a href="{prefix}index.html#contact">Контакты</a></div></footer></body></html>'''
def ranks(count=10):
 return '<div class="ranking">'+''.join(f'<div class="rank"><span class="position">{i:02d}</span><strong>{E(n)}</strong><span class="value">{v}</span></div>' for i,(n,v) in enumerate(developers[:count],1))+'</div>'
def complex_cards(count=10):
 return '<div class="grid complex">'+''.join(f'<article class="card reveal" data-class="{E(c)}"><span class="badge">{E(c)}</span><h3>{E(n)}</h3><p>{E(t)}</p><span class="developer">{E(d)}</span></article>' for n,c,t,d in complexes[:count])+'</div>'
def blog_cards(prefix=''):
 return '<div class="grid">'+''.join(f'<a class="card blog-card reveal" href="{prefix}blog/{a["slug"]}/"><span class="badge">{a["category"]}</span><h3>{a["title"]}</h3><p>{a["description"]}</p><span class="meta">Редакционный материал · 3 минуты</span></a>' for a in articles)+'</div>'
def filters():
 return '<div class="tags" aria-label="Класс жилого комплекса">'+''.join(f'<button class="tag" data-filter="{x}" aria-pressed="{str(x=="Все").lower()}">{x}</button>' for x in ['Все','Комфорт','Бизнес','Премиум','Элитный','Новая Москва'])+'</div>'
notes_dev=f'<p class="rank-note">Объём текущего строительства в Москве на 01.10.2026. Данные ЕРЗ в публикации <a class="source" href="{IRN}" target="_blank" rel="noopener">IRN от 02.10.2026</a>. Размер компании не определяет качество конкретного дома. Фонд реновации представлен отдельно от коммерческого рынка.</p>'
notes_complex=f'<p class="method">Победители отдельных номинаций <a class="source" href="{URBAN}" target="_blank" rel="noopener">Московской премии Urban 2025</a>. Карточки не упорядочены по качеству: каждый проект оценивался в своей категории. Дата проверки: 04.10.2026.</p>'
steps=[('Ваш образ жизни','Работа, семья, привычные маршруты. Сначала определяем, какой должна быть жизнь в новом доме.'),('Ваш полный бюджет','Цена покупки, ремонт, переезд и содержание. Сравниваем расходы целиком.'),('Ваш короткий список','Район, планировка, застройщик и документы. У каждого варианта должны быть понятные плюсы и ограничения.')]
step_cards='<div class="grid">'+''.join(f'<div class="card reveal"><span class="num">0{i}</span><h3>{t}</h3><p>{v}</p></div>' for i,(t,v) in enumerate(steps,1))+'</div>'
home=f'''<section class="hero"><div class="wrap"><div class="eyebrow">Жилая недвижимость · Москва и область</div><h1>Не просто квартира.<br><span>Ваше место в городе.</span></h1><p class="lead">Анастасия Шубина<br>Эксперт по жилой недвижимости Москвы и Подмосковья.</p><div class="actions"><a class="button" href="#contact">Обсудить покупку</a><a class="button secondary" href="guide/">Как выбрать квартиру</a></div></div><div class="city"><img src="assets/moscow.jpg" width="2000" height="1500" alt="Вечерняя панорама Москвы: историческая высотка и башни Москва-Сити" fetchpriority="high"><div class="city-caption"><strong>Москва. Ваша следующая глава.</strong>Квартира начинается с понимания города.</div></div></section>
<section class="section"><div class="wrap about"><div class="about-mark reveal" aria-hidden="true">АШ.</div><div class="reveal"><div class="eyebrow">Личный подход</div><h2>Выбирайте дом.<br>С пониманием деталей.</h2><p>Здесь — ориентиры для покупки квартиры в Москве и области: как сравнить районы, разобраться в планировках и оценить проекты застройщиков.</p><p>Начните с того, что важно именно вам. Затем переходите к конкретным домам.</p><a class="section-link" href="#contact">Обсудить ваши критерии</a></div></div></section>
<section class="section muted" id="choose"><div class="wrap"><div class="section-head reveal"><div><div class="eyebrow">Как выбрать квартиру</div><h2>Три шага.<br>Одно важное решение.</h2></div><p>Удобная квартира — та, которая подходит вашей жизни, а не только красиво выглядит на плане.</p></div>{step_cards}<a class="section-link" href="guide/">Открыть руководство по выбору</a></div></section>
<section class="section dark" id="developers"><div class="wrap"><div class="section-head reveal"><div><div class="eyebrow">Рейтинг застройщиков Москвы</div><h2>Кто строит город.</h2></div><p>Лидеры по объёму строительства. Проверяем масштаб, затем изучаем конкретный проект.</p></div>{ranks(5)}{notes_dev}<a class="section-link" href="developers/">Посмотреть топ-10</a></div></section>
<section class="section muted" id="complexes"><div class="wrap"><div class="section-head reveal"><div><div class="eyebrow">Рейтинг ЖК Москвы</div><h2>Дома, о которых<br>стоит узнать больше.</h2></div><p>Архитектура, среда и качество жизни. Проекты, отмеченные отраслевой премией.</p></div>{notes_complex}{complex_cards(6)}<a class="section-link" href="complexes/">Все комплексы и номинации</a></div></section>
<section class="section" id="blog"><div class="wrap"><div class="section-head reveal"><div><div class="eyebrow">Блог · Полезное о недвижимости</div><h2>Разобраться.<br>И выбрать спокойнее.</h2></div><p>Короткие руководства о районе, планировке и бюджете будущей квартиры.</p></div>{blog_cards()}<a class="section-link" href="blog/">Все материалы</a></div></section>
<section class="section" id="contact"><div class="wrap"><div class="contact reveal"><div class="eyebrow">Анастасия Шубина</div><h2>Начнём с вашей<br>будущей квартиры.</h2><p>Расскажите, где вы хотите жить, какой бюджет рассматриваете и что для вас важно в новом доме.</p><div class="actions"><a class="button" href="https://vk.ru/id_1000000000" target="_blank" rel="noopener">Написать во ВКонтакте</a><a class="button secondary" href="https://www.instagram.com/nastia_shubina/" target="_blank" rel="noopener">Instagram</a></div></div></div></section>'''
(P/'index.html').write_text(shell('Анастасия Шубина — эксперт по жилой недвижимости Москвы и области','Выбор квартиры в Москве и Подмосковье: районы, планировки, рейтинги застройщиков и жилых комплексов. Сайт Анастасии Шубиной.',home))
pages={
'developers':('Рейтинг застройщиков Москвы — октябрь 2026','Топ-10 застройщиков Москвы по объёму текущего строительства. Источник, дата и ограничения рейтинга.',f'<section class="section dark"><div class="wrap"><a class="back" href="../">Главная</a><div class="eyebrow" style="margin-top:40px">01 октября 2026</div><h1>Рейтинг застройщиков<br>Москвы.</h1><p class="lead" style="margin-left:0">Десять лидеров по объёму текущего строительства.</p>{ranks()}{notes_dev}</div></section>'),
'complexes':('Рейтинг ЖК Москвы — победители Urban Awards 2025','Жилые комплексы Москвы, отмеченные Urban Awards 2025: бизнес, премиум, элитный и комфорт-класс.',f'<section class="section"><div class="wrap"><a class="back" href="../">Главная</a><div class="eyebrow" style="margin-top:40px">Москва · Новая Москва</div><h1>Рейтинг ЖК.<br>По своей категории.</h1>{notes_complex}{filters()}{complex_cards()}</div></section>'),
'blog':('Блог о недвижимости Москвы — Анастасия Шубина','Руководства по выбору района, планировки и бюджета квартиры в Москве и области.',f'<section class="section"><div class="wrap"><a class="back" href="../">Главная</a><div class="eyebrow" style="margin-top:40px">Недвижимость без лишней сложности</div><h1>Полезно знать.<br>До покупки.</h1>{blog_cards("../")}</div></section>'),
'guide':('Как выбрать квартиру в Москве — руководство покупателя','Как выбрать квартиру: сравнение района, бюджета, планировки и жилого комплекса.',f'<div class="wrap article"><a class="back" href="../">Главная</a><h1>Как выбрать квартиру<br>в Москве.</h1><p class="intro">Начните с условий вашей жизни. После этого сравнивать дома будет проще.</p><h2>1. Запишите обязательные условия</h2><p>Укажите район или максимальное время в пути, количество комнат, бюджет и срок переезда. Разделите требования на обязательные и желательные.</p><h2>2. Проверьте район вживую</h2><p>Пройдите обычные маршруты утром и вечером. Оцените шум, пешеходные пути, магазины и зелёные зоны. Смотрите отдельно на существующую инфраструктуру и планы.</p><h2>3. Сравните планировки в масштабе</h2><p>Расставьте вашу мебель на плане. Проверьте хранение, проходы, свет и возможность использовать комнаты под разные задачи.</p><h2>4. Изучите документы и конкретный корпус</h2><p>Для новостройки найдите проектную декларацию, сведения о застройщике и сроках в ЕИСЖС. Для вторичного жилья состав документов и проверок зависит от истории квартиры и участников сделки.</p><p><a class="source" href="https://наш.дом.рф/" target="_blank" rel="noopener">ЕИСЖС: наш.дом.рф</a></p><h2>5. Посчитайте стоимость переезда целиком</h2><p>Включите ремонт, мебель, оформление, содержание и расходы на жильё до переезда. Сравнивайте варианты на одинаковом горизонте времени.</p><a class="button" href="../index.html#contact">Обсудить выбор квартиры</a></div>')}
for route,(title,desc,body) in pages.items():
 (P/route).mkdir(exist_ok=True);(P/route/'index.html').write_text(shell(title,desc,body,route+'/',1))
for a in articles:
 route='blog/'+a['slug']+'/'
 body='<div class="wrap article"><a class="back" href="../">Все материалы</a><h1>'+a['title']+'</h1><p class="intro">'+a['description']+'</p><p>Редакционный материал · 04 октября 2026</p>'+''.join('<h2>'+E(h)+'</h2><p>'+E(t)+'</p>' for h,t in a['sections'])+'<a class="button" href="../../index.html#contact">Обсудить выбор квартиры</a></div>'
 (P/route).mkdir(parents=True,exist_ok=True);(P/route/'index.html').write_text(shell(a['title']+' — Блог Анастасии Шубиной',a['description'],body,route,2,True))
(P/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80"><rect width="80" height="80" rx="20" fill="#17191c"/><text x="40" y="52" text-anchor="middle" font-family="Arial" font-size="34" fill="white">АШ</text></svg>')
routes=['']+[r+'/' for r in pages]+['blog/'+a['slug']+'/' for a in articles]
(P/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+SITE+'/'+r+'</loc></url>' for r in routes)+'</urlset>')
(P/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+SITE+'/sitemap.xml\n')
(P/'.nojekyll').touch()
(P/'404.html').write_text(shell('Страница не найдена','Перейдите на главную страницу сайта Анастасии Шубиной.','<div class="wrap article"><h1>Здесь пока пусто.</h1><p>Вернитесь на главную и выберите нужный раздел.</p><a class="button" href="'+SITE+'/">На главную</a></div>'))
print('Built',len(routes),'indexable pages')
